/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_jni_jniprojectdemo_JniJava */

#ifndef _Included_com_ndk_jni_jniprojectdemo_JniJava
#define _Included_com_ndk_jni_jniprojectdemo_JniJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_jni_jniprojectdemo_JniJava
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndk_jni_jniprojectdemo_JniJava_getCString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
